name: readorsee-v2
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - asn1crypto=1.3.0
  - attrs=19.3.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.0
  - bz2file=0.98
  - ca-certificates=2020.1.1
  - certifi=2020.4.5.1
  - cffi=1.14.0
  - chardet=3.0.4
  - cloudpickle=1.3.0
  - colorama=0.4.3
  - cryptography=2.8
  - cudatoolkit=10.1.243
  - cudnn=7.6.5
  - cycler=0.10.0
  - cytoolz=0.10.1
  - dask-core=2.14.0
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - freetype=2.9.1
  - icc_rt=2019.0.0
  - icu=58.2
  - idna=2.9
  - imageio=2.8.0
  - importlib_metadata=1.5.0
  - intel-openmp=2020.0
  - ipykernel=5.1.4
  - ipython=7.13.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.16.0
  - jinja2=2.11.1
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.2
  - jupyter_console=6.1.0
  - jupyter_core=4.6.3
  - kiwisolver=1.1.0
  - libiconv=1.15
  - libpng=1.6.37
  - libsodium=1.0.16
  - libtiff=4.1.0
  - libxml2=2.9.9
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=1.1.1
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - mistune=0.8.4
  - mkl=2020.0
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - msys2-conda-epoch
  - nbconvert=5.6.1
  - nbformat=5.0.4
  - networkx=2.4
  - ninja=1.9.0
  - notebook=6.0.3
  - numpy=1.18.1
  - numpy-base=1.18.1
  - olefile=0.46
  - openssl=1.1.1
  - pandas=1.0.3
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.6.2
  - pcre=8.43
  - pickleshare=0.7.5
  - pillow=7.0.0
  - pip=20.0.2
  - prometheus_client=0.7.1
  - prompt-toolkit=3.0.4
  - prompt_toolkit=3.0.4
  - pycparser=2.20
  - pygments=2.6.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.6
  - pyqt=5.9.2
  - pyrsistent=0.16.0
  - pysocks=1.7.1
  - python=3.7.7
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytorch=1.4.0
  - pytz=2019.3
  - pywavelets=1.1.1
  - pywin32=227
  - pywinpty=0.5.7
  - pyzmq=18.1.1
  - qt=5.9.7
  - qtconsole=4.7.2
  - qtpy=1.9.0
  - requests=2.23.0
  - scikit-image=0.16.2
  - scipy=1.4.1
  - seaborn=0.10.0
  - send2trash=1.5.0
  - setuptools=46.1.1
  - sip=4.19.8
  - six=1.14.0
  - smart_open=1.9.0
  - sqlite=3.31.1
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.8
  - toolz=0.10.0
  - torchvision=0.5.0
  - tornado=6.0.4
  - traitlets=4.3.3
  - urllib3=1.25.8
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - wcwidth=0.1.9
  - webencodings=0.5.1
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - winpty=0.4.3
  - xz=5.2.4
  - zeromq=4.3.1
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - alabaster==0.7.12
    - allennlp==0.9.0
    - atomicwrites==1.3.0
    - babel==2.8.0
    - blis==0.2.4
    - boto==2.49.0
    - boto3==1.12.39
    - botocore==1.15.39
    - click==7.1.1
    - conllu==1.3.1
    - cymem==2.0.3
    - docutils==0.15.2
    - editdistance==0.5.3
    - filelock==3.0.12
    - flaky==3.6.1
    - flask==1.1.2
    - flask-cors==3.0.8
    - ftfy==5.7
    - gensim==3.8.1
    - gevent==1.5.0
    - greenlet==0.4.15
    - h5py==2.10.0
    - imagesize==1.2.0
    - importlib-metadata==1.6.0
    - itsdangerous==1.1.0
    - jmespath==0.9.5
    - joblib==0.14.1
    - jsonpickle==1.3
    - liwc==0.5.0
    - matplotlib-venn==0.11.5
    - more-itertools==8.2.0
    - murmurhash==1.0.2
    - nltk==3.4.5
    - numpydoc==0.9.2
    - overrides==2.8.0
    - packaging==20.3
    - parsimonious==0.8.1
    - plac==0.9.6
    - pluggy==0.13.1
    - preshed==2.0.1
    - protobuf==3.11.3
    - pt-core-news-sm==2.1.0
    - py==1.8.1
    - pytest==5.4.1
    - python-dotenv==0.12.0
    - pytorch-pretrained-bert==0.6.2
    - pytorch-transformers==1.1.0
    - regex==2020.4.4
    - responses==0.10.12
    - s3transfer==0.3.3
    - sacremoses==0.0.38
    - scikit-learn==0.22.2.post1
    - sentencepiece==0.1.85
    - smart-open==1.11.1
    - snowballstemmer==2.0.0
    - spacy==2.1.9
    - sphinx==3.0.1
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==1.0.3
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.4
    - sqlparse==0.3.1
    - srsly==1.0.2
    - tensorboardx==2.0
    - thinc==7.0.8
    - tokenizers==0.5.2
    - tqdm==4.45.0
    - transformers==2.8.0
    - unidecode==1.1.1
    - wasabi==0.6.0
    - werkzeug==1.0.1
    - word2number==1.1
    - zipp==3.1.0

